name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish the Docker image
      run: docker build . --file Dockerfile --tag amitg90/python-helloworld
      run: docker login --username amitg90 --password grover420
      run: docker push amitg90/python-helloworld

