name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        id: step1
        run: docker build . --file Dockerfile --tag amitg90/python-helloworld
      - name: Docker login image
        id: step2
        run: docker login --username amitg90 --password grover420
      - name: Docker push image
        id: step3
        run: docker push amitg90/python-helloworld

