name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag amitg90/python-helloworld
      - name: Docker login image
        run: docker login --username aaa --password bbb
      - name: Docker push image
        run: docker push amitg90/python-helloworld

